# -*- coding: utf-8 -*-
"""CodeAlpha_IrisFlowerClassification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sx4_n7eU_Z7QoefWnp0WagpOhtkt73o_
"""

#Import required libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import zipfile, os
from google.colab import files

#Upload your archive.zip file
uploaded = files.upload()

# Unzip the file
with zipfile.ZipFile("archive.zip", "r") as zip_ref:
    zip_ref.extractall("iris_data")

#Load the dataset
iris = pd.read_csv("iris_data/Iris.csv")
iris = iris.drop(columns=["Id"])   # Drop ID column

#Split features and target
X = iris.drop(columns=["Species"])
y = iris["Species"]

#Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Train model
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

# Evaluate model
y_pred = model.predict(X_test)
print("\n✅ Model Trained Successfully")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Get manual input from user
print("\nEnter flower measurements:")
sepal_length = float(input("Sepal Length (cm): "))
sepal_width  = float(input("Sepal Width (cm): "))
petal_length = float(input("Petal Length (cm): "))
petal_width  = float(input("Petal Width (cm): "))

sample_input = [[sepal_length, sepal_width, petal_length, petal_width]]

# Predict
prediction = model.predict(sample_input)
print("\n🌸 Predicted Species for your input:", prediction[0])